_wandb:
    value:
        cli_version: 0.22.3
        e:
            ls65smjff7kdsgd23fygkz5m1vssr1hs:
                args:
                    - "3"
                codePath: train_matry_sae.py
                codePathLocal: train_matry_sae.py
                cpu_count: 10
                cpu_count_logical: 12
                disk:
                    /:
                        total: "1003736440832"
                        used: "216271106048"
                email: s.setlur@sms.ed.ac.uk
                executable: /home/s2721407/miniconda3/envs/interplm/bin/python
                git:
                    commit: f574a945f4bbe050752b36c36c89548f24f302f8
                    remote: git@github.com:siddharthsetlur/ProteinLens.git
                host: s2721407-HP-EliteBook-840-14-inch-G10-Notebook-PC
                memory:
                    total: "15922941952"
                os: Linux-6.14.0-33-generic-x86_64-with-glibc2.39
                program: /home/s2721407/Desktop/ProteinLens/train_matry_sae.py
                python: CPython 3.11.13
                root: /home/s2721407/Desktop/ProteinLens
                startedAt: "2025-11-17T20:02:48.305623Z"
                writerId: ls65smjff7kdsgd23fygkz5m1vssr1hs
        m: []
        python_version: 3.11.13
        t:
            "1":
                - 1
                - 11
                - 49
                - 71
            "2":
                - 1
                - 11
                - 49
                - 71
            "3":
                - 2
                - 13
                - 16
                - 61
            "4": 3.11.13
            "5": 0.22.3
            "6": 4.44.0
            "12": 0.22.3
            "13": linux-x86_64
data_config:
    value:
        batch_size: 128
        n_shards_to_include: null
        plm_embd_dir: /home/s2721407/Desktop/ProteinLens/data/esm2_8m/layer_4
        samples_to_skip: 0
        seed: 0
        target_dtype: torch.float32
        zscore_means_file: null
        zscore_vars_file: null
evaluation_config:
    value:
        corrupt: false
        eval_batch_size: 8
        eval_embd_dir: null
        eval_seq_path: /home/s2721407/Desktop/ProteinLens/data/eval_sequences.txt
        eval_steps: 10000
        layer_idx: 4
        model_name: esm2_t6_8M_UR50D
        target_dtype: torch.float32
        zscore_means_file: null
        zscore_vars_file: null
trainer_config:
    value:
        activation_dim: 320
        auxk_alpha: 0.03125
        dead_feature_threshold: 10000000
        decay_start: 8000
        dictionary_size: 1280
        epochs: 0.9412464084018627
        expansion_factor: 4
        group_fractions:
            - 0.125
            - 0.125
            - 0.25
            - 0.5
        group_weights:
            - 0.25
            - 0.25
            - 0.25
            - 0.25
        k: 30
        k_anneal_steps: null
        lr: 0.0002
        normalize_to_sqrt_d: false
        resample_steps: null
        steps: 9500
        threshold_beta: 0.999
        threshold_start_step: 1000
        warmup_steps: 1000
