wandb_version: 1

trainer_config:
  desc: null
  value:
    expansion_factor: 4.0
    dictionary_size: 1280
    lr: 0.0002
    activation_dim: 320
    epochs: 0.9610520991401112
    steps: 9500
    warmup_steps: 1000
    decay_start: 8000
    resample_steps: null
    normalize_to_sqrt_d: false
    l1_penalty: 0.06
    l1_penalty_warmup_steps: 475
data_config:
  desc: null
  value:
    plm_embd_dir: /Users/siddharthsetlur/Desktop/PhD/ProteinLens/data/training_embeddings/esm2_8m/layer_4
    batch_size: 128
    seed: 0
    samples_to_skip: 0
    n_shards_to_include: null
    zscore_means_file: null
    zscore_vars_file: null
    target_dtype: torch.float32
evaluation_config:
  desc: null
  value:
    eval_seq_path: /Users/siddharthsetlur/Desktop/PhD/ProteinLens/data/eval_sequences.txt
    eval_embd_dir: null
    eval_batch_size: 8
    eval_steps: 10000
    zscore_means_file: null
    zscore_vars_file: null
    target_dtype: torch.float32
    model_name: esm2_t6_8M_UR50D
    layer_idx: 4
    corrupt: false
_wandb:
  desc: null
  value:
    python_version: 3.11.13
    cli_version: 0.17.6
    framework: huggingface
    huggingface_version: 4.44.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1762997837
    t:
      1:
      - 1
      - 11
      - 49
      - 55
      - 71
      3:
      - 13
      - 16
      - 23
      4: 3.11.13
      5: 0.17.6
      6: 4.44.0
      8:
      - 5
      13: darwin-x86_64
